# Generated by Django 4.2.8 on 2024-03-16 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('name',), 'verbose_name': 'Skill', 'verbose_name_plural': 'Skill'},
        ),
    ]
