# Generated by Django 4.2.8 on 2024-03-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('school_name', models.CharField(blank=True, default='', max_length=254, verbose_name='School Name')),
                ('major', models.CharField(blank=True, default='', max_length=254, verbose_name='Major')),
                ('department', models.CharField(blank=True, default='', max_length=254, verbose_name='Department')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, default=None, null=True, verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ('-start_date',),
            },
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ('-start_date',), 'verbose_name': 'Experience', 'verbose_name_plural': 'Experience'},
        ),
    ]
