# Generated by Django 4.2.8 on 2024-03-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_socialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('name', models.CharField(blank=True, default='', help_text='This is veriable of swttings', max_length=254, verbose_name='Name')),
                ('button_text', models.CharField(blank=True, default='', max_length=254, verbose_name='Button Text')),
                ('file', models.ImageField(blank=True, default='', max_length=254, upload_to='documents/')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Document',
                'ordering': ('order',),
            },
        ),
    ]
