# Generated by Django 4.2.8 on 2024-03-16 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_document_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
    ]
